# Generated by Django 6.0.3 on 2026-04-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_lecture_options_alter_course_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='test_field',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
