# Generated by Django 6.0.3 on 2026-04-06 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_lecture_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='test_field',
        ),
    ]
