# Generated by Django 6.0.3 on 2026-04-06 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_lecture_test_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='ترتيب المحاضرة (1، 2، 3...)'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='video_url',
            field=models.URLField(help_text='ارمي هنا أي لينك يوتيوب (عادي، Shorts، أو مختصر)'),
        ),
    ]
