# Generated by Django 6.0.3 on 2026-04-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_lecture_order_alter_lecture_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='HonorRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150)),
                ('rank_description', models.CharField(help_text='مثال: الأولى على محافظة كفر الشيخ', max_length=200)),
                ('image', models.ImageField(blank=True, help_text='اختياري: صورة الطالب', null=True, upload_to='honor_roll/')),
            ],
            options={
                'verbose_name': 'لوحة الشرف',
                'verbose_name_plural': 'لوحة الشرف',
            },
        ),
        migrations.CreateModel(
            name='TeacherSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='الأستاذ محمد عيد', max_length=100)),
                ('main_image', models.ImageField(help_text='ارفع صورة المستر الكبيرة هنا', upload_to='teacher_info/')),
                ('intro_video_url', models.URLField(help_text='لينك يوتيوب للفيديو التعريفي')),
                ('philosophical_quote', models.TextField(default='الفلسفة ليست مادة تحفظ، بل هي عقل يفكر وحياة تُعاش.')),
            ],
            options={
                'verbose_name': 'إعدادات الجنرال (الرئيسية)',
                'verbose_name_plural': 'إعدادات الجنرال (الرئيسية)',
            },
        ),
        migrations.AlterField(
            model_name='lecture',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='ترتيب المحاضرة'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='video_url',
            field=models.URLField(help_text='ارمي هنا أي لينك يوتيوب'),
        ),
    ]
