# Generated by Django 6.0.3 on 2026-04-06 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_honorroll_teachersettings_alter_lecture_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'كورس / شهر', 'verbose_name_plural': 'الكورسات (الشهور)'},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'بروفايل طالب', 'verbose_name_plural': 'بروفايلات الطلاب'},
        ),
        migrations.AddField(
            model_name='course',
            name='grade',
            field=models.CharField(choices=[('1', 'الصف الأول الثانوي'), ('2', 'الصف الثاني الثانوي'), ('3', 'الصف الثالث الثانوي')], default='3', max_length=2, verbose_name='مخصص لسنة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(verbose_name='وصف محتوى الشهر'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/', verbose_name='غلاف الكورس'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, verbose_name='اسم الكورس (مثلاً: شهر أكتوبر)'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='video_url',
            field=models.URLField(help_text='رابط فيديو اليوتيوب'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='governorate',
            field=models.CharField(max_length=50, verbose_name='المحافظة'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='grade',
            field=models.CharField(choices=[('1', 'الصف الأول الثانوي'), ('2', 'الصف الثاني الثانوي'), ('3', 'الصف الثالث الثانوي')], max_length=20, verbose_name='السنة الدراسية'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='تم تفعيل الحساب'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='parent_phone',
            field=models.CharField(max_length=15, verbose_name='رقم ولي الأمر'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='رقم الطالب'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='system',
            field=models.CharField(choices=[('general', 'عام'), ('azhar', 'أزهري')], max_length=20, verbose_name='النظام'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='الاشتراك مفعل')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'اشتراك طالب',
                'verbose_name_plural': 'اشتراكات الطلاب (الدفع)',
                'unique_together': {('student', 'course')},
            },
        ),
    ]
