# Generated by Django 6.0.3 on 2026-04-06 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_course_options_alter_studentprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'اشتراك طالب', 'verbose_name_plural': 'اشتراكات الطلاب'},
        ),
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['order'], 'verbose_name': 'محاضرة', 'verbose_name_plural': 'المحاضرات'},
        ),
        migrations.AddField(
            model_name='enrollment',
            name='allowed_lectures_count',
            field=models.PositiveIntegerField(default=1, verbose_name='عدد المحاضرات المفتوحة له'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الاشتراك'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course', verbose_name='الكورس (الشهر)'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتيب المحاضرة'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='lectures_pdf/', verbose_name='ملف PDF للمحاضرة'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان المحاضرة'),
        ),
    ]
