# Generated by Django 6.0.3 on 2026-04-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_enrollment_options_alter_lecture_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='system',
            field=models.CharField(choices=[('general', 'عام'), ('azhar', 'أزهري'), ('bac', 'بكالوريا'), ('all', 'الكل (عام وأزهري وبكالوريا)')], default='all', max_length=10, verbose_name='مخصص لنظام'),
        ),
    ]
