# Generated by Django 6.0.3 on 2026-04-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_course_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachersettings',
            name='intro_video_url',
        ),
        migrations.AddField(
            model_name='teachersettings',
            name='intro_video',
            field=models.FileField(blank=True, help_text='ارفع الفيديو التعريفي من جهازك مباشرة (MP4)', null=True, upload_to='teacher_videos/'),
        ),
    ]
