# Generated by Django 6.0.3 on 2026-04-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_teachersettings_intro_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='system',
            field=models.CharField(choices=[('general', 'عام'), ('azhar', 'أزهري'), ('bakaloria', 'بكالوريا')], max_length=20, verbose_name='النظام'),
        ),
    ]
