# Generated by Django 6.0.3 on 2026-08-30 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_studentprofile_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الامتحان')),
                ('is_comprehensive', models.BooleanField(default=False, verbose_name='امتحان شامل؟')),
                ('duration_mins', models.IntegerField(default=30, verbose_name='مدة الامتحان بالدقائق')),
                ('lecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='main.lecture', verbose_name='تابع لمحاضرة (اختياري)')),
            ],
            options={
                'verbose_name': 'امتحان',
                'verbose_name_plural': '📝 الامتحانات',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='نص السؤال')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions_images/', verbose_name='صورة مع السؤال (اختياري)')),
                ('choice1', models.CharField(max_length=255, verbose_name='الاختيار الأول')),
                ('choice2', models.CharField(max_length=255, verbose_name='الاختيار الثاني')),
                ('choice3', models.CharField(max_length=255, verbose_name='الاختيار الثالث')),
                ('choice4', models.CharField(max_length=255, verbose_name='الاختيار الرابع')),
                ('correct_answer', models.CharField(choices=[('1', 'الاختيار الأول'), ('2', 'الاختيار الثاني'), ('3', 'الاختيار الثالث'), ('4', 'الاختيار الرابع')], max_length=1, verbose_name='الإجابة الصحيحة')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.exam', verbose_name='الامتحان')),
            ],
            options={
                'verbose_name': 'سؤال',
                'verbose_name_plural': '❓ الأسئلة',
            },
        ),
    ]
