# Generated by Django 6.0.3 on 2026-08-30 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_exam_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='parent_phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_parent',
        ),
        migrations.AddField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='main.course', verbose_name='التابع لكورس'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='ParentProfile',
        ),
    ]
